### ISSUE TITLE
Capitalization Issues

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/D365PostsBot#1]
My username got added to the storage table all lower case, but when the notification to process, it was mixed case, and the user was not found!

**Comment by daryllabar** [comment]
The two places where I just to lower:

Here
![image](https://user-images.githubusercontent.com/9728423/174462652-4e88151f-ded1-431e-9b30-3f37eb5823cd.png)

And Here:
![image](https://user-images.githubusercontent.com/9728423/174462670-4f737b9e-7bb9-44f2-8530-e1808f13c96d.png)

**Comment by MarkMpn** [comment]
Thanks, I've pushed a fix to convert it to lowercase for any new users, but check for both versions when looking for a user to send a post to in case they were added with the original casing.
